// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"github.com/google/uuid"
)

type File struct {
	ID      uuid.UUID `json:"id"`
	LinkID  uuid.UUID `json:"link_id"`
	FileUrl string    `json:"file_url"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type Folder struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type Link struct {
	ID       uuid.UUID `json:"id"`
	Url      string    `json:"url"`
	Excerpt  string    `json:"excerpt"`
	CoverUrl string    `json:"cover_url"`
	OwnerID  uuid.UUID `json:"owner_id"`
	FolderID uuid.UUID `json:"folder_id"`
}

type LinkMedia struct {
	ID       uuid.UUID `json:"id"`
	LinkID   uuid.UUID `json:"link_id"`
	MediaUrl string    `json:"media_url"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type Tag struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	FullName string    `json:"full_name"`
	Password string    `json:"password"`
}
