// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"github.com/google/uuid"
)

type File struct {
	ID      uuid.UUID `json:"id"`
	Linkid  uuid.UUID `json:"linkid"`
	Fileurl string    `json:"fileurl"`
	Ownerid uuid.UUID `json:"ownerid"`
}

type Folder struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Ownerid uuid.UUID `json:"ownerid"`
}

type Link struct {
	ID       uuid.UUID `json:"id"`
	Url      string    `json:"url"`
	Excerpt  string    `json:"excerpt"`
	Coverurl string    `json:"coverurl"`
	Ownerid  uuid.UUID `json:"ownerid"`
	Folderid uuid.UUID `json:"folderid"`
}

type LinkMedium struct {
	ID       uuid.UUID `json:"id"`
	Linkid   uuid.UUID `json:"linkid"`
	Mediaurl string    `json:"mediaurl"`
	Ownerid  uuid.UUID `json:"ownerid"`
}

type Tag struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Ownerid uuid.UUID `json:"ownerid"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Fullname string    `json:"fullname"`
	Password string    `json:"password"`
}
